// Generated by CoffeeScript 1.10.0
(function() {
  var assert, assertContainsSvg, checkLoadCount, isvg, renderComponent, span;

  assert = chai.assert;

  isvg = ReactInlineSVG;

  span = React.DOM.span;

  renderComponent = function(component) {
    var div;
    div = document.createElement('div');
    div.style.display = 'none';
    document.body.appendChild(div);
    React.renderComponent(component, div);
    return div;
  };

  assertContainsSvg = function(el, done) {
    if ($(el).find('svg').length) {
      return done();
    } else {
      return done(new Error('Missing SVG'));
    }
  };

  checkLoadCount = function(url, handleLoad, counter, done) {
    counter.push('call');
    console.dir(counter);
    console.log(counter.length);
    if (counter.length > 1) {
      return done(new Error('too many calls'));
    } else {
      return handleLoad(null, '<path d="M8 5v14l11-8z"/>') && done();
    }
  };

  describe('react-inlinesvg', function() {
    it('should request an SVG only once when caching', function(done) {
      var counter, el;
      counter = [];
      el = renderComponent(isvg({
        src: 'https://raw.githubusercontent.com/google/material-design-icons/master/av/svg/production/ic_play_arrow_24px.svg',
        loadResource: function(url, handleLoad) {
          return checkLoadCount(url, handleLoad, counter, done);
        },
        onError: done
      }));
      return el = renderComponent(isvg({
        src: 'https://raw.githubusercontent.com/google/material-design-icons/master/av/svg/production/ic_play_arrow_24px.svg',
        loadResource: function(url, handleLoad) {
          return checkLoadCount(url, handleLoad, counter, done);
        },
        onError: done
      }));
    });
    it('should load an svg', function(done) {
      var el;
      return el = renderComponent(isvg({
        src: 'tiger.svg',
        onError: done,
        onLoad: function() {
          return assertContainsSvg(el, done);
        }
      }));
    });
    it('should load a base64 data-uri', function(done) {
      var el;
      return el = renderComponent(isvg({
        src: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICAgIDxwYXRoIGQ9Ik04IDV2MTRsMTEtN3oiLz4KICAgIDxwYXRoIGQ9Ik0wIDBoMjR2MjRIMHoiIGZpbGw9Im5vbmUiLz4KPC9zdmc+Cg==',
        onError: done,
        onLoad: function() {
          return setTimeout((function() {
            return assertContainsSvg(el, done);
          }), 0);
        }
      }));
    });
    it('should load a non-base64 data-uri', function(done) {
      var el;
      return el = renderComponent(isvg({
        src: 'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2224%22%20height%3D%2224%22%20viewBox%3D%220%200%2024%2024%22%3E%0A%20%20%20%20%3Cpath%20d%3D%22M8%205v14l11-7z%22%2F%3E%0A%20%20%20%20%3Cpath%20d%3D%22M0%200h24v24H0z%22%20fill%3D%22none%22%2F%3E%0A%3C%2Fsvg%3E%0A',
        onError: done,
        onLoad: function() {
          return setTimeout((function() {
            return assertContainsSvg(el, done);
          }), 0);
        }
      }));
    });
    it('should call onError for a 404', function(done) {
      return renderComponent(isvg({
        src: 'DOESNOTEXIST.svg',
        onError: function() {
          return done();
        }
      }));
    });
    it('should load SVGs from a CORS-enabled domain', function(done) {
      var el;
      return el = renderComponent(isvg({
        src: 'http://localhost:1338/test/tiger.svg',
        onError: done,
        onLoad: function() {
          return assertContainsSvg(el, done);
        }
      }));
    });
    it('should should show children if loading not supported', function(done) {
      var el;
      return el = renderComponent(isvg({
        src: 'DOESNOTEXIST.svg',
        supportTest: function() {
          return false;
        },
        onError: function(err) {
          if (/MISSINGNO/.test(el.innerHTML)) {
            return done();
          } else {
            return done(new Error('Missing fallback contents'));
          }
        }
      }, span(null, ''), span(null, 'MISSINGNO')));
    });
    it('should should NOT show children on error', function(done) {
      var el;
      return el = renderComponent(isvg({
        src: 'DOESNOTEXIST.svg',
        onError: function() {
          if (/MISSINGNO/.test(el.innerHTML)) {
            return done(new Error('Children shown even though loading is supported'));
          } else {
            return done();
          }
        }
      }, span(null, 'MISSINGNO')));
    });
    return describe('errors', function() {
      return it('should have a status code HTTP errors', function(done) {
        return renderComponent(isvg({
          src: 'DOESNOTEXIST.svg',
          onError: function(err) {
            if (err.isHttpError && err.status === 404) {
              return done();
            } else {
              return done(new Error('Error missing information'));
            }
          }
        }));
      });
    });
  });

}).call(this);
